baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Joseph Carlson'

[[menus.main]]
name = 'My Thoughts'
pageRef = '/my-thoughts'
weight = 10

[[menus.main]]
name = 'Case Studies'
pageRef = '/case-studies'
weight = 20

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 30